spring.application.name=auth-service
server.port=4005

spring.datasource.url=jdbc:postgresql://auth-service-db:5432/db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=fAyKgVpvwKEvtkoiI3MxHa2f8yK8s5It3VFXX875AK2