### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "John Doe kafka",
    "email": "test_billing_example3434jdhf@example.com",
    "address": "123 main streetss",
    "dateOfBirth": "1995-09-09",
   "registeredDate": "2004-08-01"

}


###